// localhost
### Get all users
GET http://localhost:3001/users

### Get user by id
GET http://localhost:3001/users/65ec8dbbc2e08b6dafa1e7fe

### Create user
POST http://localhost:3001/users HTTP/1.1
content-type: application/json

{    
  "username": "joseluis@mail.com",
  "email": "joseluis@chris",
  "name": "Jose Luis",
  "ipaddress": "94.321.168.53"
  }

### PUT user
PUT http://localhost:3001/users/65ec85640780fc83ac52b97c
Content-Type: application/json

{    
 "username": "joseluis@mail.com",
  "email": "joseluis@chris",
  "name": "Jose Luis",
  "ipaddress": "94.321.168.53"
  }

### DELETE user
DELETE http://localhost:3001/users/65ec9cf59779167d6ce14676

// PRODUCTION
### Home Page
GET https://cse341-node-x3ll.onrender.com/

### Get all users
GET https://cse341-node-x3ll.onrender.com/users

### Get user by id
GET https://cse341-node-x3ll.onrender.com/users/65ec8dbbc2e08b6dafa1e7fe

### Get swagger
GET https://cse341-node-x3ll.onrender.com/api-docs/
